# This is a basic workflow to help you get started with Actions

name: Gif Comment

# Controls when the action will run. 
on:
  issues:
    types: [opened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  comment:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: Add funny comment
        uses: jgetzel/Lab5_PartyHorn@v1
        id: FunnyComment
        with:
          GITHUB_TOKEN:  ${{secrets.GITHUB_TOKEN}}
          GIPHY_TOKEN: ${{secrets.GIPHY_TOKEN}}
          comment_type: 'gif'
